### ISSUE TITLE
Could not copy the file "/app/gdata.json" because it was not found.

### ISSUE THREAD

**Issue by FlameYagami** [Tlaster/ehdb#4]
大佬 我下了Website的分支 解压到了D盘 执行ocker-compose up指令 出现了以下错误 应该如何解决？
/usr/share/dotnet/sdk/2.2.401/Microsoft.Common.CurrentVersion.targets(4552,5): error MSB3030: Could not copy the file "/app/gdata.json" because it was not found. [/app/EHDB.csproj]
ERROR: Service 'server' failed to build: The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1

**Comment by Tlaster** [comment]
从mega吧`gdata.json`下下来然后丢到`./site/server`目录下
现在在更新网站相关内容，没有及时更新文档
