### ISSUE TITLE
Need more powerful search function.

### ISSUE THREAD

**Issue by tiny-vest** [Tlaster/ehdb#8]
You can type like below in e-hentai srarch bar to searching multiple tags. Hope this project can add same function.
```
language:chinese$ "full color$" female:stockings$
```

**Comment by firefoxchan** [comment]
If you don't mind running the server locally, (shameless plug) you could check this repo: https://github.com/firefoxchan/local-ehentai

Supports multi tags search, expunged / min-rating filter, local thumbnails cache, export search results to csv / json, etc.

**Comment by Tlaster** [comment]
As Exhentai back online now you can just use Exhentai directly.
